### ISSUE TITLE
Parse int larger than u8

### ISSUE THREAD

**Issue by rupurt** [Hejsil/zig-clap#103]
Currently it looks like you can only parse integer arguments represented as `u8`.

I get the following error when trying to use `u16`:

```zig
    const params = comptime clap.parseParamsComptime(
        \\-h, --help                       Display this help and exit.
        \\-l, --line-buffer <LINEBUFFER>   An option parameter, which takes a value.
        \\<FILE1>                          The base file
        \\<FILE2>                          The file to compare
        \\
    );
    const parsers = comptime .{
        .LINEBUFFER = clap.parsers.int(u16, 1024),
        .FILE1 = clap.parsers.string,
        .FILE2 = clap.parsers.string,
    };
```

```shell
src/main.zig:17:45: error: type 'u8' cannot represent integer value '1024'
```

The tests only cover `u8` https://github.com/Hejsil/zig-clap/blob/master/clap/parsers.zig#L39

**Comment by Hejsil** [comment]
The second argument to `clap.parsers.int` is the `radix` aka, the base in which we parse the number. For `10`, this means that `"10" => 10`. For `2` this means `"10" => 2`. I don't think the standard library `parseInt` supports base `1024`.

**Comment by Hejsil** [comment]
I could rename it from `radix` to base to make this more clear. I think the standard library used to call it `radix`, but changed to `base` at some point after I wrote that function. Consistency is hard :)

**Comment by Hejsil** [comment]
This seems to be a misunderstanding of what the second argument of `clap.parsers.int` does. I've added some documentation to the function in [this PR](https://github.com/Hejsil/zig-clap/pull/104). Hopefully that should avoid future confusion

**Comment by rupurt** [comment]
Ah, gotcha!

Thanks for the clarification. That's just me being a newb in zig... More docs are always welcome though 😄 Thanks for the useful library!
