### ISSUE TITLE
Create a tag to line up with zon version 0.7.0

### ISSUE THREAD

**Issue by softprops** [Hejsil/zig-clap#109]
The zon version for this lib is [set to 0.7.0 ](https://github.com/Hejsil/zig-clap/blob/c394594d218c3c936547e590b461e69e6e0b20c4/build.zig.zon#L3) but the latest tag is 0.4.0. 

Can you push a 0.7.0 for that release so that I can use a url for the release in my clap client exe?

**Comment by softprops** [comment]
My bad. it [does exist ](https://github.com/Hejsil/zig-clap/tree/0.7.0)

**Comment by Hejsil** [comment]
I noticed that `0.6.0` was shown as the latest release. I've fixed that :)
