### ISSUE TITLE
Argument parsing in function

### ISSUE THREAD

**Issue by notramo** [Hejsil/zig-clap#110]
I want to refactor argument parsing into a separate function. It would parse the arguments, and validate them (min/max for numbers, permissions for file paths, etc.), then return the result of the parse function.

```zig
// use it in main()
pub fn main() {
  // ...
  const validatedArgs = parseAndValidateArgs(
    // ...
  );
}

pub fn parseAndValidateArgs() { // what is the return type?
  // ...
  const cliArgs = clap.parse(
    // ...
  );

  // validate here

  // then return
  return cliArgs;
}
```

How do I specify the return type of the `parseAndValidateArgs` function in the above snippet? Is there a clean and readable way of doing it?

**Comment by Hejsil** [comment]
There is `clap.Result`. Its the function that generates the return type for `clap.parse`.

**Comment by notramo** [comment]
@Hejsil could you provide an example usage in the above snippet? Simply putting it as `clap.Result` into the return type definition doesn't work. Do I have to use something like `@Type(clap.Result)`?

**Comment by Hejsil** [comment]
Something along the lines of this:

```zig
const params = ...;

pub fn parseAndValidateArgs() !clap.Result(clap.Help, params, clap.parsers.default) {
  const cliArgs = try clap.parse(clap.Help, params, clap.parsers.default);

  // validate here

  // then return
  return cliArgs;
}
```

**Comment by notramo** [comment]
It works, thank you.
