### ISSUE TITLE
Default values for arguments?

### ISSUE THREAD

**Issue by jaywonchung** [Hejsil/zig-clap#116]
If there a specific syntax to specify custom default values for arguments? For instance, I want `-t, --temperature` to be `0.9` if the user never specifies that option on the command line. Thanks a lot.

**Comment by Hejsil** [comment]
No, this is currently not supported. It's not really something I've thought too much about, since you can quite easily do a default when getting the value:

```zig
const temp = args.args.temperature orelse 0.9;
```

**Comment by jaywonchung** [comment]
Oh I see! That's good enough for me as well. Thanks.
