### ISSUE TITLE
Backward compatibility?

### ISSUE THREAD

**Issue by jinzhongjia** [Hejsil/zig-clap#128]
At present, I have encountered the problem of being unable to compile with 12 when using the latest clap. I don’t know if backward compatibility can be guaranteed.

The development cycle of 13 is only two months

If possible I can open pr to patch this

**Comment by jinzhongjia** [comment]
My goal is to make the program compile with both 13 and 12
Because the current zig versions of various Linux distributions are 0.12 and 0.13

**Comment by Hejsil** [comment]
I see. This is not something I've ever tried. If you have something simple then I might be willing to merge it. Ofc, I can't promise that every zig-clap release will compile for multiple zig releases

**Comment by jinzhongjia** [comment]
I understand what you mean. This issue only exists because 12 and 13 are only two months apart.
