### ISSUE TITLE
Have a plan for using into build.zig?

### ISSUE THREAD

**Issue by ritalin** [Hejsil/zig-clap#135]
I'd like to use this module into `build.zig`.
Using `const clap = @import("clap")` into `build.zig` in my project led to load `build.zig` of `zig-clap`.
Because a loaded file id not a module but a builder, It will fail to build.

Do you have a plan for using into build.zig?

IMO, it will resolve in `build.zig` following:

```zig
const std = @import("std");
+ pub usingnamespace @import("clap.zig"); // add this line
// (snip) following code
```

**Comment by Hejsil** [comment]
Sorry, but I don't understand what you're suggesting/asking 😓

**Comment by aikawayataro** [comment]
I guess he's asking for feature when you can access module from `build.zig`, like this: https://zig.news/liyu1981/how-to-use-your-fav-pkg-in-buildzig-3ni8
I can't see a valid reason for this though

**Comment by Hejsil** [comment]
Aah I see. Yea, I don't see a valid reason to do this either. `zig build` handles arguments for `build.zig` so using `zig-clap` in `build.zig` wouldn't be wise.

**Comment by ritalin** [comment]
OK, I see.
