### ISSUE TITLE
zig 0.6.0, error: expected type 'std.build.Id', found '*const [10:0]u8'

### ISSUE THREAD

**Issue by phdye** [Hejsil/zig-clap#19]
Using zig version 0.6.0+51682717d

./build.zig:62:31: error: expected type 'std.build.Id', found '*const [10:0]u8'
    s.* = std.build.Step.init("ReadMeStep", b.allocator, struct {
                              ^
/home/phdyex/host-specific/local/lib/zig/std/build.zig:2430:20: note: std.build.Id declared here
    pub const Id = enum {
                   ^
Thanks

**Comment by Hejsil** [comment]
Hi, it seems you're using Zig master. This repo currently targets the Zig 0.6.0 release. There is a `zig-master` branch that is meant to be kept up to date with Zig master, but this branch is kept up to date by people who use Zig master (not me).

**Comment by phdye** [comment]
got it.  I'll sort that out.  Thanks.
