### ISSUE TITLE
Incompatibility with 32bit builds

### ISSUE THREAD

**Issue by pedromsilvapt** [Hejsil/zig-clap#23]
Hi. I was trying to build for target `i386-windows` and got this error:
```
.\lib\clap\clap.zig:293:38: error: expected type 'usize', found 'u64'
                res = counting_stream.bytes_written;
```

I think res is `usize` but `bytes_written` is always u64, and that's causing the conflict.

**Comment by Hejsil** [comment]
Thanks for the issue! I believe I fixed it in the latest commit :)
