### ISSUE TITLE
`clap.help` with proper line wrapping

### ISSUE THREAD

**Issue by Hejsil** [Hejsil/zig-clap#28]
Currently, we just write the help message to a stream without thinking about wrapping or anything. This is simple, but it's not that great for long help messages, as the default terminal wrapping ruins the help messages format.

I think the solution here is to rework the api a little:
* Have `clap.help` only take an array of `Param(Help)` and have it fetch stderr + tty width internally.
* Have new flexible versions of `clap.help` which can be given a stream.

**Comment by squeek502** [comment]
A possible alternative (or complementary feature) would be to do indenting for each new line in a description string so that the user could insert newlines to get the wrapping they desire.

Example:

```
    const params = comptime [_]clap.Param(clap.Help){
        clap.parseParam("-h, --help    Display this help and exit.") catch unreachable,
        clap.parseParam("--foo         This\nis\na\ndescription\nover\nmultiple\nlines.") catch unreachable,
        clap.parseParam("--bar         Something else.") catch unreachable,
    };
```

Right now this would give:
```
	-h, --help	Display this help and exit.
	    --foo 	This
is
a
description
over
multiple
lines.
	    --bar 	Something else.
```

But it could give:
```
	-h, --help	Display this help and exit.
	    --foo 	This
	                is
                        a
                        description
                        over
                        multiple
                        lines.
	    --bar 	Something else.
```

**Comment by Hejsil** [comment]
I see. I think both would be nice. Clap should both wrap text automatically and respect newlines in the description string for formatting. I'll probably merge that in if you make a PR :)
