### ISSUE TITLE
Add support for arguments that are not tokenized yet

### ISSUE THREAD

**Issue by kristoff-it** [Hejsil/zig-clap#30]
This is a slightly esoteric use case, but at a first glance it doesn't seem too hard to support. 

I'd like to be able to feed to clap a argument string that hasn't been tokenized yet. 
At the moment, I'm implementing my own custom ArgIterator, but I think having this implemented inside clap itself might be a good way of reusing (at least some of) the parsing logic that you already have.

To give a bit more context on the usecase: I want to allow users of zig-doctest to specify build options as a special comment in the first line of the script itself.

**Comment by Hejsil** [comment]
I'm not sure I completely understand what you want here. Have some example code of what it is you want to do?

**Comment by Hejsil** [comment]
Was clarified on stream. Basically what is wanted here is an arg iterator that takes a string and parses into arguments like what a shell does.

**Comment by Hejsil** [comment]
Try out the new `clap.args.ShellIterator` :+1:
