### ISSUE TITLE
cannot format slice without a specifier (i.e. {s} or {any})

### ISSUE THREAD

**Issue by nfisher1226** [Hejsil/zig-clap#38]
On branch zig-master, zig current seems to demand a format specifier for stream.print. In file clap.zig lines 275-278.
```
            error.DoesntTakeValue => try stream.print("The argument '{}{}' does not take a value\n", .{ a.prefix, a.name }),
            error.MissingValue => try stream.print("The argument '{}{}' requires a value but none was supplied\n", .{ a.prefix, a.name }),
            error.InvalidArgument => try stream.print("Invalid argument '{}{}'\n", .{ a.prefix, a.name }),
            else => try stream.print("Error while parsing arguments: {}\n", .{@errorName(err)}),
````
I'm new to zig, adding 's' in each parens seems to work?

**Comment by Hejsil** [comment]
Yep, that should be the fix. Care to do a PR?

**Comment by Dhole** [comment]
Hi! I noticed that this issue has already been fixed in https://github.com/Hejsil/zig-clap/pull/41
I believe this issue can now be closed.

**Comment by Hejsil** [comment]
You are correct! :confetti_ball:
