### ISSUE TITLE
`chainging` typo

### ISSUE THREAD

**Issue by canadaduane** [Hejsil/zig-clap#58]
Just FYI there are a few refs to `chainging` in the source code... I think it's a typo?

**Comment by Hejsil** [comment]
Haven't had a look at where these are yet, but they are probably typos :sweat_smile:

**Comment by canadaduane** [comment]
Sorry for my post's brevity! I was in a rush last night. Here are the lines I saw:

https://github.com/Hejsil/zig-clap/blob/master/clap/streaming.zig#L49
https://github.com/Hejsil/zig-clap/blob/master/clap/streaming.zig#L92
https://github.com/Hejsil/zig-clap/blob/master/clap/streaming.zig#L113

Thanks for zig-clap!
