### ISSUE TITLE
infinite loop in parseEx, "while (try stream.next())"

### ISSUE THREAD

**Issue by BlueAlmost** [Hejsil/zig-clap#72]
Experiencing the infinite loop issue in the parseEx "while (try stream.next())" code.

I see there is a "TODO" mentioning that a fix to this is blocked by compiler bugs which are causing the infinite loop.

Is there a suggested work around to avoid this?  Or has the compiler possibly changed recently in a way to allow a work around?

**Comment by Hejsil** [comment]
Hmm. There really shouldn't be. The todo is about a different way of writing that code that causes an infinite loop. Can you post the code that causes this?

**Comment by BlueAlmost** [comment]
Hej Hejsil,

Thanks for your message.

This evening I will try to trim my code and share a simple example code
snippet.

Best,

James

**Comment by BlueAlmost** [comment]
Good Evening Komari,

I have attached the simplified example of the infinite loop that I had been
experiencing.

Bear in mind, that I may have been doing something completely wrong.  If
so, I apologize in advance.

I had been using earlier clap version and it had worked nicely for my FFT
experiments.  I had attempted
to learn the newer version of clap, when I ran into this loop issue.

The contents of the infinite_loop.taz file are:

build.zig - my build file
clap.zig - the latest from the github repository (note: I have added a
debug.print statement to show the looping)
clap/  -  directory from the github
framework.zig - a simplified example (main)
command_line_config.zig - my function to parse the comman line
failure.sh - this is a bash shell script to call the file which produces
the looping behaviour.

Thanks for the excellent clap software, and double thanks for having a look
at this example.

Best Regards,
James

**Comment by BlueAlmost** [comment]
[InfLoop.zip](https://github.com/Hejsil/zig-clap/files/8318752/InfLoop.zip)

(I realized that the email with a tar file probably would not reach you ... so I dragged and dropped the zip file here in github...
Cheers,
James

**Comment by Hejsil** [comment]
Thanks code sample. This is the same bug as the comment points out. I thought I had worked around it but apparently not. Here is the reduced test case:
```zig
test "str and u64" {
    const params = comptime &.{
        parseParam("--str <str>") catch unreachable,
        parseParam("--num <u64>") catch unreachable,
    };

    var iter = args.SliceIterator{
        .args = &.{ "--num", "10", "--str", "cooley_rec_inp_ptr" },
    };
    var res = try parseEx(Help, params, parsers.default, &iter, .{
        .allocator = testing.allocator,
    });
    defer res.deinit();
}
```

Time to have a look.

**Comment by Hejsil** [comment]
What a fun bug. I've worked around it for now. I'm pretty sure this is a know bug in the compiler so hopefully this will be fixed soon :)

**Comment by BlueAlmost** [comment]
Thanks very much!  The work around functions nicely!
