### ISSUE TITLE
A Zig'y way of constructing the clap

### ISSUE THREAD

**Issue by Hejsil** [Hejsil/zig-clap#8]
> I don't think the java 'builder' way of doing things is really 'Zig'y, and I prefer the syntax way of the current arg.zig which honestly looks very nice; 

Now, I'm not aware of what exactly he means by not 'Zig'y, but I have my own problems with the Builder pattern I'm using:
* The indent level explodes quite fast with my current coding style.
* `zig fmt` will ruine code written this way.
* The builders them self are around 30% of the code in `clap.zig`
* All the `.build()` at the end are ugly, and I don't like them.

We need a way to constructs arguments, which allows for the following:
* Allows for optional, and required "arguments" to the construction of options.
  * I require that the user specifies the field, which an argument is mapped to, but the rest, I provide sensible defaults for, which can be overwritten if the user wants (This is the strength of the Builder Pattern)
* Unlike `arg.zig` in the self hosted parser, arguments can have be long, short or both.
  * The reason we destinguish is to allow short arguments to chain: `-abcd`

@BraedonWooding I'd love to hear what you think. Any idea of a better way?

**Comment by BraedonWooding** [comment]
Basically it came down to the fact that zig code typically doesn't use builder patterns, from what I mostly see and view the culture is around utilising type ducking rather than builders, as builders often produce as you stated code that explodes in terms of indents, but also very boilerplate 'builder' styles (eventually leading to builders for your builders, which you kinda already have though not in any extreme way), and the need for finish commands.  I ran into the same problems and I really only found the 'ugly' side of doing this when I was writing my own package manager purely in build.zig.

The way I kinda 'envision' it is;
```C
const OptionsSpec = struct { 
  h: ?Spec.Flag(bool), // Note: the `?` to signify optional, the type is specified but idk if it needs to be
  fileName: Spec.Arg([]const u8), // This one isn't optional
  inputFiles: Spec.ManyArg([]const u8), // Multiple can be an empty set too so adding an optional would be well probably a compile error, like whats the difference between no items and 'null'; no functional difference
  state: Spec.Option(int, 1, 0, -1), // Var args?  Though maybe we may need to take in a slice due to the fact that var args don't work at compile time still I think

  // We can utilise these fields which are quite nice to hold user data
  pub const Author = "Author";
  pub const Version = "v1.0";
  pub const AutogenDoc = true;
};
```

Then you would call it something like;
```C
const parser = comptime Clap(OptionsSpec);
const args = try os.argsAlloc(debug.global_allocator);
defer os.argsFree(debug.global_allocator, args);

const options = try parser.parse(args[1..]);
if (options.h.value) |val| {
   debug.warn("Value is: {}", val);
}

for (options.inputFiles.next()) |file| {
   // Do whatever
}
```

Now what this lacks is the fact that it requires some compile time reflection which I think is fine and the nice'ness of this really makes up for it.  However it doesn't allow you to have both a long and a short form, HOWEVER I think this could be accomplished via an option like;
```C
... = struct {
...
// Note: if you have "" as one of the lengths then it WON'T allow that length
// Otherwise it'll presume `--` for all ones bigger than 1 character else `-`
printFiles: Spec.Flag(bool).SpecifyLength("p", "print-files"),
...
}
```
Again this is taking a little bit of the builder pattern however I think Zig typically avoids builder patterns unless it is to do with types where it typically uses them to chain types.

Now the interesting thing about this solution is it avoids ANY sub modules commands, however those could be added as an option, such that you could have a master spec that holds a series of smaller specs.  Again I think the benefit is that it is easier to read and doesn't strain from indents.

As a final note: You would have sub commands like;
```C
const MasterSpec = struct {
   ...
   build: Spec.SubCommand(struct {
       h: Spec.Flag(bool),
       ...
   }),
   ....
}

// Or you could define it else where and just call it like `build: Spec.SubCommand(BuildSpec),`
const BuildSpec = struct {
   h: Spec.Flag(bool),
}
```

What do you think about this?

**Comment by Hejsil** [comment]
A very nice write-up. I overall like it, but I see two problem already.

Let's say that you have some core library. The library has an `Option` struct you can send through its api. All you want to do is provide a frontend. With this solution, you can't, because you probably don't want to edit the core library, and you probably don't want clap as a dependency in the core.

And what if you want more frontends? A "Json" frontend that uses the same system to construct the `Option`. A GUI, that uses the same system to map elements in the struct to UI elements.

The problem here is, that this solution pollutes the type. I would personally prefer if we had a solution that didn't do that (because I kinda need it. The example above is problems I would encounter with my [pokemon randomizer](https://github.com/Hejsil/pokemon-randomizer)).

**Comment by andrewrk** [comment]
I was thinking, perhaps we could introduce a feature of structs where fields can have "tags". This would be an array of any comptime expressions that the user could add to the field.

Something like:

```zig
const Foo = struct {
    x: u32 @("anything") @(bar()),
};

fn bar() i32 {
    return 1234;
}
```

Then with reflection you could get access to a field's tags.

**Comment by BraedonWooding** [comment]
Ahhh kinda like that attribute thing I was talking about, something purely based upon reflection.  I think that would be brilliant for serialisation in general!

**Comment by Hejsil** [comment]
@andrewrk I like the idea of tags, but that only makes @BraedonWooding proposal nicer and doesn't solve this "I can't edit this struct, because it's part of a lib" problem :)

**Comment by andrewrk** [comment]
I think this is a fundamental problem with argument parsers - at the end of the day there's nothing more flexible than manually iterating over the args and then doing exactly what you want to do with each one. To use an argument parser is to accept that the data will go to an intermediate location before being in the final useful form. Maybe this can be mitigated with a configuration that accepts pointers for where to store each data item. This would let you populate fields of structs that one does not control the definition of.

**Comment by Hejsil** [comment]
Well, the current version works without polluting the type.
```
Argument.Builder
    .init("a") // The field to set, when this argument is found
    .short('a')
    .takesValue(true)
    .build(),
```

I possible, I wanna preserve this. If not, then I guess one could always copy everything from the result of clap, to the actual struct.

**Comment by BraedonWooding** [comment]
However by not polluting you lose expressiveness I guess, and it becomes a little more wieldy to use.  Not by much though.  The tags I feel is a nice middle ground, they don't add pollution however they make it very expressive still.

Note: if you wanted you could have the library take a compile time struct for its arg spec therefore you could pass it a different one and due to generics it 'should' work perfectly fine as long as you followed a few of their 'base' rules.

**Comment by Hejsil** [comment]
@BraedonWooding That is true, though generic everywhere gives less good error messages.

For now, I think the builders will stay, and I just work on some other features. When/If we get "tags" in Zig we can look into this again :)

**Comment by andrewrk** [comment]
> Well, the current version works without polluting the type.

Oh! I had missed this detail. This is really quite beautiful and clever.

**Comment by Hejsil** [comment]
We now use the functional `with` pattern (idk the name for it), instead of builders:
```
const clap = comptime Clap(Options).init(default).with("command",
    Command.init("").with("arguments",
        []Argument {
            Argument.arg("a"),
            Argument.arg("b"),
            Argument.field("int")
                .with("short", 'i')
                .with("takes_value", parse.int(i64, 10))
        }
    )
);
```

It's alot nice, since `with` is implemented in 5 lines of code with `@field`. These issues still hold for this version though:
* The indent level explodes quite fast with my current coding style.
* zig fmt will ruine code written this way.

**Comment by BraedonWooding** [comment]
I’ve got to say that this is like 12 times better!  Very nice, though yes those issues still exist but aren’t so bad compared to the last version.

**Comment by Hejsil** [comment]
I'll still leave this open until we get tags. We might be able to have both worlds because we could have a function that generates the data structure above from tags. So people who don't want to pollute their types can use the above, and everyone else can generate it from a struct that has tags.

**Comment by Hejsil** [comment]
This issue is pretty old now, and the lib has changed in focus. We have no way of parsing args to fields anymore, but the new `ComptimeClap` should be just as efficient. This api looks like this:
```
const params = comptime []clap.Param(void){
    clap.Param(void).init({}, false, clap.Names.prefix("help")),
    clap.Param(void).init({}, true, clap.Names.prefix("number")),
    clap.Param(void).init({}, true, clap.Names.positional()),
};

var os_iter = clap.args.OsIterator.init(allocator);
const iter = &os_iter.iter;
defer os_iter.deinit();

const exe = try iter.next();

var args = try clap.ComptimeClap(void, params).parse(allocator, clap.args.OsIterator.Error, iter);
defer args.deinit();

if (args.flag("--help"))
    debug.warn("Help!\n");
if (args.option("--number")) |n|
    debug.warn("--number = {}\n", n);
for (args.positionals()) |pos|
    debug.warn("{}\n", pos);
```
