### ISSUE TITLE
Why the usage output is so simple?

### ISSUE THREAD

**Issue by TheWaWaR** [Hejsil/zig-clap#80]
The usage output is so simple even missing the description of the parameter. I think it's bad for user experience.

How about support usage output just like [`clap-rs`](https://github.com/clap-rs/clap/blob/master/examples/demo.md)?

```
$ demo --help
clap [..]
A simple to use, efficient, and full-featured Command Line Argument Parser

USAGE:
    demo[EXE] [OPTIONS] --name <NAME>

OPTIONS:
    -n, --name <NAME>      Name of the person to greet
    -c, --count <COUNT>    Number of times to greet [default: 1]
    -h, --help             Print help information
    -V, --version          Print version information
```

**Comment by Hejsil** [comment]
> The usage output is so simple even missing the description of the parameter.

I'm a little confused. Have you seen `clap.help`?

**Comment by TheWaWaR** [comment]
> I'm a little confused. Have you seen `clap.help`?

Oh, I see. Sorry by missing that. I think maybe better use `clap.hep()` in example code, I guess that's most users' want.

**Comment by Hejsil** [comment]
Cool. Seemed like you had missed it, but wasn't sure. Anything else, or can this be closed?

**Comment by TheWaWaR** [comment]
Nothing more. Thanks.
