### ISSUE TITLE
Seems you have crashed the compiler. A way to work around this is to use the stage1 compiler. This is done by either passing `-fstage1` to `zig build-exe` or setting the `exe.stage1` field to `true` in your `build.zig` file.

### ISSUE THREAD

**Issue by Khaledhfjv** [Hejsil/zig-clap#85]
Seems you have crashed the compiler. A way to work around this is to use the stage1 compiler. This is done by either passing `-fstage1` to `zig build-exe` or setting the `exe.stage1` field to `true` in your `build.zig` file.

I'll have a look around to see if the has been reported to zig

_Originally posted by @Hejsil in https://github.com/Hejsil/zig-clap/issues/84#issuecomment-1328310834_

**Comment by Hejsil** [comment]
I'm confused? Why did you open an issue which is just a copy paste of a comment I made?

**Comment by Hejsil** [comment]
Please comment on #84 if there is something related you wonna share. I'll close this
